apiVersion: v1
kind: ReplicationController
metadata: 
  name: tomcat
spec: 
  replicas: 2
  selector: 
    app: tomcat
  template: 
    metadata: 
      labels: 
        app: tomcat
    spec: 
      containers: 
          - name: tomcat
            image: "tomcat:8.0.18-jre8"
            ports: 
                - containerPort: 8080
