---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandraa
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    interface: cassandraa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandrab
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    interface: cassandrab
